vich_uploader:
    db_driver: orm

    mappings:
        articles_images:
            uri_prefix: /images/uploads/articles
            upload_destination: '%kernel.project_dir%/public/images/uploads/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
